import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Container, Flex } from "@chakra-ui/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Mpc Wallet Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Container maxW="100vw" minHeight="100vh" bg="orange.50">
            <Flex justifyContent="center" alignItems="center" minHeight="100vh">
              {children}
            </Flex>
          </Container>
        </Provider>
      </body>
    </html>
  );
}
